DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_df__candidate__1_4_3;
DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_df__previous__1_4_3;
DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3;

