DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_shadow_1_2_0;

CREATE TABLE youmei_sandbox.dwd_trade_order_shadow_1_2_0
(
    snapshot_date Date COMMENT '数据快照日期',
    shop_id String COMMENT '店铺ID',
    shop_name Nullable(String) COMMENT '店铺名称',
    shop_order_id String COMMENT '店铺订单号',
    order_level_code Nullable(String) COMMENT '订单层级编码',
    business_source_code Nullable(String) COMMENT '业务来源编码',
    business_source_name Nullable(String) COMMENT '业务来源名称',
    order_type_code Nullable(String) COMMENT '订单类型编码',
    order_type_name Nullable(String) COMMENT '订单类型名称',
    trade_type_code Nullable(String) COMMENT '交易类型编码',
    trade_type_name Nullable(String) COMMENT '交易类型名称',
    order_status_code Nullable(String) COMMENT '订单状态编码',
    order_status_name Nullable(String) COMMENT '订单状态名称',
    main_status_code Nullable(String) COMMENT '主流程状态编码',
    main_status_name Nullable(String) COMMENT '主流程状态名称',
    order_entry_code Nullable(String) COMMENT '下单端编码',
    order_entry_name Nullable(String) COMMENT '下单端名称',
    order_scene_code Nullable(String) COMMENT '下单场景编码',
    order_scene_name Nullable(String) COMMENT '下单场景名称',
    payment_type_code Nullable(String) COMMENT '支付方式编码',
    channel_payment_no Nullable(String) COMMENT '支付渠道流水号',
    app_id Nullable(String) COMMENT '小程序ID',
    paid_at Nullable(DateTime('Asia/Shanghai')) COMMENT '支付时间',
    order_expired_at Nullable(DateTime('Asia/Shanghai')) COMMENT '订单过期时间',
    finished_at Nullable(DateTime('Asia/Shanghai')) COMMENT '订单完成时间',
    created_at Nullable(DateTime('Asia/Shanghai')) COMMENT '下单时间',
    updated_at Nullable(DateTime('Asia/Shanghai')) COMMENT '订单更新时间',
    expected_ship_at Nullable(DateTime('Asia/Shanghai')) COMMENT '预计发货时间',
    shipped_at Nullable(DateTime('Asia/Shanghai')) COMMENT '发货时间',
    cancel_reason Nullable(String) COMMENT '取消原因',
    buyer_words Nullable(String) COMMENT '买家留言',
    seller_words Nullable(String) COMMENT '商家备注',
    encrypted_post_phone Nullable(String) COMMENT '加密收件人电话',
    encrypted_post_receiver Nullable(String) COMMENT '加密收件人姓名',
    post_address Nullable(String) COMMENT '收件人地址',
    masked_post_receiver Nullable(String) COMMENT '脱敏收件人姓名',
    masked_post_phone Nullable(String) COMMENT '脱敏收件人电话',
    masked_post_address Nullable(String) COMMENT '脱敏收件人地址',
    pay_phone Nullable(String) COMMENT '下单人手机号',
    post_receiver Nullable(String) COMMENT '收件人姓名',
    post_phone Nullable(String) COMMENT '收件人电话',
    open_address_id Nullable(String) COMMENT '收件人地址ID',
    greet_words Nullable(String) COMMENT '贺卡文字',
    order_amount Nullable(Decimal128(2)) COMMENT '订单金额，源单位分，清洗后单位元',
    paid_amount Nullable(Decimal128(2)) COMMENT '支付金额，源单位分，清洗后单位元',
    freight_amount Nullable(Decimal128(2)) COMMENT '快递费，源单位分，清洗后单位元',
    freight_insurance_amount Nullable(Decimal128(2)) COMMENT '运费险金额，源单位分，清洗后单位元',
    price_adjust_amount Nullable(Decimal128(2)) COMMENT '改价金额变化量，源单位分，清洗后单位元',
    freight_adjust_amount Nullable(Decimal128(2)) COMMENT '改价运费金额变化量，源单位分，清洗后单位元',
    promotion_amount Nullable(Decimal128(2)) COMMENT '订单优惠总金额，源单位分，清洗后单位元',
    shop_promotion_amount Nullable(Decimal128(2)) COMMENT '店铺优惠金额，源单位分，清洗后单位元',
    platform_promotion_amount Nullable(Decimal128(2)) COMMENT '平台优惠金额，源单位分，清洗后单位元',
    talent_promotion_amount Nullable(Decimal128(2)) COMMENT '达人优惠金额，源单位分，清洗后单位元',
    payment_promotion_amount Nullable(Decimal128(2)) COMMENT '支付优惠金额，源单位分，清洗后单位元',
    redpack_promotion_amount Nullable(Decimal128(2)) COMMENT '红包优惠金额，源单位分，清洗后单位元',
    redpack_platform_promotion_amount Nullable(Decimal128(2)) COMMENT '平台红包优惠金额，源单位分，清洗后单位元',
    redpack_talent_promotion_amount Nullable(Decimal128(2)) COMMENT '达人红包优惠金额，源单位分，清洗后单位元',
    shop_cost_amount Nullable(Decimal128(2)) COMMENT '商家承担金额，源单位分，清洗后单位元',
    platform_cost_amount Nullable(Decimal128(2)) COMMENT '平台承担金额，源单位分，清洗后单位元',
    only_platform_cost_amount Nullable(Decimal128(2)) COMMENT '仅平台承担金额，源单位分，清洗后单位元',
    author_cost_amount Nullable(Decimal128(2)) COMMENT '达人承担金额，源单位分，清洗后单位元',
    post_origin_amount Nullable(Decimal128(2)) COMMENT '运费原价，源单位分，清洗后单位元',
    post_promotion_amount Nullable(Decimal128(2)) COMMENT '运费优惠金额，源单位分，清洗后单位元',
    total_promotion_amount Nullable(Decimal128(2)) COMMENT '总优惠金额，源单位分，清洗后单位元',
    packing_amount Nullable(Decimal128(2)) COMMENT '打包费，源单位分，清洗后单位元'
)
ENGINE = MergeTree
PARTITION BY snapshot_date
ORDER BY (snapshot_date, shop_id, shop_order_id);

INSERT INTO youmei_sandbox.dwd_trade_order_shadow_1_2_0
WITH normalized AS
(
    SELECT DISTINCT
        toDate(dt) AS snapshot_date,
        nullIf(trim(shop_id), '') AS shop_id,
        nullIf(trim(shop_name), '') AS shop_name,
        nullIf(trim(order_id), '') AS shop_order_id,
        nullIf(trim(order_level), '') AS order_level_code,
        nullIf(trim(biz), '') AS business_source_code,
        nullIf(trim(biz_desc), '') AS business_source_name,
        nullIf(trim(order_type), '') AS order_type_code,
        nullIf(trim(order_type_desc), '') AS order_type_name,
        nullIf(trim(trade_type), '') AS trade_type_code,
        nullIf(trim(trade_type_desc), '') AS trade_type_name,
        nullIf(trim(order_status), '') AS order_status_code,
        nullIf(trim(order_status_desc), '') AS order_status_name,
        nullIf(trim(main_status), '') AS main_status_code,
        nullIf(trim(main_status_desc), '') AS main_status_name,
        nullIf(trim(b_type), '') AS order_entry_code,
        nullIf(trim(b_type_desc), '') AS order_entry_name,
        nullIf(trim(sub_b_type), '') AS order_scene_code,
        nullIf(trim(sub_b_type_desc), '') AS order_scene_name,
        nullIf(trim(pay_type), '') AS payment_type_code,
        nullIf(trim(channel_payment_no), '') AS channel_payment_no,
        nullIf(trim(app_id), '') AS app_id,
        if(toInt64OrNull(nullIf(pay_time, '')) IS NULL OR toInt64OrZero(pay_time) = 0, NULL, toDateTime(toInt64OrZero(pay_time), 'Asia/Shanghai')) AS paid_at,
        if(toInt64OrNull(nullIf(order_expire_time, '')) IS NULL OR toInt64OrZero(order_expire_time) = 0, NULL, toDateTime(toInt64OrZero(order_expire_time), 'Asia/Shanghai')) AS order_expired_at,
        if(toInt64OrNull(nullIf(finish_time, '')) IS NULL OR toInt64OrZero(finish_time) = 0, NULL, toDateTime(toInt64OrZero(finish_time), 'Asia/Shanghai')) AS finished_at,
        if(toInt64OrNull(nullIf(create_time, '')) IS NULL OR toInt64OrZero(create_time) = 0, NULL, toDateTime(toInt64OrZero(create_time), 'Asia/Shanghai')) AS created_at,
        if(toInt64OrNull(nullIf(update_time, '')) IS NULL OR toInt64OrZero(update_time) = 0, NULL, toDateTime(toInt64OrZero(update_time), 'Asia/Shanghai')) AS updated_at,
        if(toInt64OrNull(nullIf(exp_ship_time, '')) IS NULL OR toInt64OrZero(exp_ship_time) = 0, NULL, toDateTime(toInt64OrZero(exp_ship_time), 'Asia/Shanghai')) AS expected_ship_at,
        if(toInt64OrNull(nullIf(ship_time, '')) IS NULL OR toInt64OrZero(ship_time) = 0, NULL, toDateTime(toInt64OrZero(ship_time), 'Asia/Shanghai')) AS shipped_at,
        nullIf(trim(cancel_reason), '') AS cancel_reason,
        nullIf(trim(buyer_words), '') AS buyer_words,
        nullIf(trim(seller_words), '') AS seller_words,
        nullIf(trim(encrypt_post_tel), '') AS encrypted_post_phone,
        nullIf(trim(encrypt_post_receiver), '') AS encrypted_post_receiver,
        nullIf(trim(post_addr), '') AS post_address,
        nullIf(trim(mask_post_receiver), '') AS masked_post_receiver,
        nullIf(trim(mask_post_tel), '') AS masked_post_phone,
        nullIf(trim(mask_post_addr), '') AS masked_post_address,
        nullIf(trim(pay_tel), '') AS pay_phone,
        nullIf(trim(post_receiver), '') AS post_receiver,
        nullIf(trim(post_tel), '') AS post_phone,
        nullIf(trim(open_address_id), '') AS open_address_id,
        nullIf(trim(greet_words), '') AS greet_words,
        if(nullIf(trim(order_amount), '') IS NULL, NULL, toDecimal128OrNull(order_amount, 2) / 100) AS order_amount,
        if(nullIf(trim(pay_amount), '') IS NULL, NULL, toDecimal128OrNull(pay_amount, 2) / 100) AS paid_amount,
        if(nullIf(trim(post_amount), '') IS NULL, NULL, toDecimal128OrNull(post_amount, 2) / 100) AS freight_amount,
        if(nullIf(trim(post_insurance_amount), '') IS NULL, NULL, toDecimal128OrNull(post_insurance_amount, 2) / 100) AS freight_insurance_amount,
        if(nullIf(trim(modify_amount), '') IS NULL, NULL, toDecimal128OrNull(modify_amount, 2) / 100) AS price_adjust_amount,
        if(nullIf(trim(modify_post_amount), '') IS NULL, NULL, toDecimal128OrNull(modify_post_amount, 2) / 100) AS freight_adjust_amount,
        if(nullIf(trim(promotion_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_amount, 2) / 100) AS promotion_amount,
        if(nullIf(trim(promotion_shop_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_shop_amount, 2) / 100) AS shop_promotion_amount,
        if(nullIf(trim(promotion_platform_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_platform_amount, 2) / 100) AS platform_promotion_amount,
        if(nullIf(trim(promotion_talent_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_talent_amount, 2) / 100) AS talent_promotion_amount,
        if(nullIf(trim(promotion_pay_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_pay_amount, 2) / 100) AS payment_promotion_amount,
        if(nullIf(trim(promotion_redpack_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_redpack_amount, 2) / 100) AS redpack_promotion_amount,
        if(nullIf(trim(promotion_redpack_platform_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_redpack_platform_amount, 2) / 100) AS redpack_platform_promotion_amount,
        if(nullIf(trim(promotion_redpack_talent_amount), '') IS NULL, NULL, toDecimal128OrNull(promotion_redpack_talent_amount, 2) / 100) AS redpack_talent_promotion_amount,
        if(nullIf(trim(shop_cost_amount), '') IS NULL, NULL, toDecimal128OrNull(shop_cost_amount, 2) / 100) AS shop_cost_amount,
        if(nullIf(trim(platform_cost_amount), '') IS NULL, NULL, toDecimal128OrNull(platform_cost_amount, 2) / 100) AS platform_cost_amount,
        if(nullIf(trim(only_platform_cost_amount), '') IS NULL, NULL, toDecimal128OrNull(only_platform_cost_amount, 2) / 100) AS only_platform_cost_amount,
        if(nullIf(trim(author_cost_amount), '') IS NULL, NULL, toDecimal128OrNull(author_cost_amount, 2) / 100) AS author_cost_amount,
        if(nullIf(trim(post_origin_amount), '') IS NULL, NULL, toDecimal128OrNull(post_origin_amount, 2) / 100) AS post_origin_amount,
        if(nullIf(trim(post_promotion_amount), '') IS NULL, NULL, toDecimal128OrNull(post_promotion_amount, 2) / 100) AS post_promotion_amount,
        if(nullIf(trim(total_promotion_amount), '') IS NULL, NULL, toDecimal128OrNull(total_promotion_amount, 2) / 100) AS total_promotion_amount,
        if(nullIf(trim(packing_amount), '') IS NULL, NULL, toDecimal128OrNull(packing_amount, 2) / 100) AS packing_amount
    FROM youmei_sandbox.ods_api_dd_sale_order_list_info_f
    WHERE dt = '2026-07-22'
)
SELECT *
FROM normalized
WHERE shop_id IS NOT NULL
  AND shop_order_id IS NOT NULL;
