DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3__candidate__1_3_3;
DROP TABLE IF EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3__previous__1_3_3;
