CREATE TABLE IF NOT EXISTS youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3
AS youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3__candidate__1_3_3;

RENAME TABLE
    youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3
        TO youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3__previous__1_3_3,
    youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3__candidate__1_3_3
        TO youmei_sandbox.dwd_trade_order_logistics_tracking_no_shadow_1_3_3;
